// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import Navbar from './navbar'
// import Footer from './footer'
// import Booking from './booking'
// import { ChakraProvider } from '@chakra-ui/react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Terkar Capital',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     // <html lang="en">
//       <ChakraProvider>
//       <body className={inter.className}>
//         <Booking />
//         <Navbar />
//         {children}
//         <Footer />
//         </body>
//     </ChakraProvider>
//     // </html>
//   )
// }

import { ReactNode } from 'react'
import Navbar from './navbar'
import Footer from './footer'
import Booking from './booking'
import type { Metadata } from 'next'
type LayoutProps = {
  children: ReactNode
}
//  export const metadata: Metadata = {
//     title: 'Shigora',
//     description: 'Generated by create next app',
//   }

const Layout = ({ children }: LayoutProps) => {
  return (
    <div className=''>
      <Booking />
      <Navbar/>
      {children}
      <Footer/>
    </div>
  )
}

export default Layout